// Characterization safety net (Platform migration, Phase 1 / #49).
//
// A golden dump of EVERY file every preset generates, so any extraction that
// changes a single generated byte fails loudly. The dumps are plain text — a
// drift shows up as an ordinary git diff. Regenerate intentionally with:
//
//   UPDATE_SNAPSHOTS=1 node --test test/characterization.test.js
//
// The generator version (packkit.json `version`) is stripped: it changes on a
// release (e.g. the 4.0.0 platform bump) and is not "generated content" drift.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { createProject } from '../src/embedded/index.js';
import { PRESET_NAMES } from '../src/core/presets.js';

const SNAP_DIR = join(dirname(fileURLToPath(import.meta.url)), '__snapshots__');
// Fixed identity → deterministic, version-independent output.
const FIXED = { author: 'Fixture Author <fixture@example.com>', description: 'A fixture project.', repo: 'https://github.com/fixture/fixture' };

function stable(path, content) {
  if (path !== 'packkit.json') return content;
  const json = JSON.parse(content);
  delete json.version;
  return `${JSON.stringify(json, null, 2)}\n`;
}

// One readable dump of every generated file, sorted for stability.
function dump(preset) {
  const { files } = createProject({ preset, name: 'fixture', config: FIXED });
  return Object.keys(files)
    .sort()
    .map((path) => `===== ${path} =====\n${stable(path, files[path])}`)
    .join('\n');
}

for (const preset of PRESET_NAMES) {
  test(`characterization: ${preset} matches its byte-parity snapshot`, () => {
    const current = dump(preset);
    assert.equal(dump(preset), current, `${preset} generation is not deterministic`);

    const file = join(SNAP_DIR, `${preset}.snap`);
    if (process.env.UPDATE_SNAPSHOTS) {
      mkdirSync(SNAP_DIR, { recursive: true });
      writeFileSync(file, current);
      return;
    }
    assert.ok(existsSync(file), `Missing snapshot for "${preset}". Run: UPDATE_SNAPSHOTS=1 node --test test/characterization.test.js`);
    assert.equal(current, readFileSync(file, 'utf8'), `"${preset}" output drifted from its snapshot — regenerate with UPDATE_SNAPSHOTS=1 to review the diff.`);
  });
}
