// create-packkit as a @packkit/core PackkitGenerator.
//
// Since 4.0 the embedded API's GeneratedProject is already protocol-native (its
// metadata is the @packkit/core shape), so this adapter is a thin wrapper: it
// advertises identity + capabilities, exposes presets/schema, and translates
// only the ProjectDefinition format (create-packkit's PackkitProjectDefinition
// <-> the platform's ProjectDefinition). The underlying machinery does the work.

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { PACKKIT_PROTOCOL_VERSION } from '@packkit/core';
import { OPTIONS, PRESET_NAMES, PRESET_INFO } from '../core/index.js';
import { GENERATOR_ID } from './constants.js';
import { packageJsonDiffer } from './manifest-differ.js';
import {
  SCHEMA_VERSION,
  createProject as ccCreateProject,
  createProjectFromDefinition as ccCreateProjectFromDefinition,
  exportProjectDefinition as ccExportProjectDefinition,
  upgradeProject as ccUpgradeProject,
} from './index.js';

const VERSION = JSON.parse(readFileSync(join(dirname(fileURLToPath(import.meta.url)), '..', '..', 'package.json'), 'utf8')).version;

function toCoreDefinition(def) {
  return {
    schemaVersion: def.schemaVersion,
    protocolVersion: PACKKIT_PROTOCOL_VERSION,
    generator: { id: GENERATOR_ID, version: def.packkitVersion },
    preset: def.preset,
    config: def.config,
    extensions: def.extensions,
  };
}

function toCreatePackkitDefinition(def) {
  return {
    schemaVersion: def.schemaVersion,
    packkitVersion: def.generator?.version,
    preset: def.preset,
    config: def.config,
    extensions: def.extensions,
  };
}

/** create-packkit implemented as a platform generator. */
export const packkitGenerator = {
  id: GENERATOR_ID,
  language: 'javascript',
  version: VERSION,
  maturity: 'stable',
  protocol: {
    version: PACKKIT_PROTOCOL_VERSION,
    capabilities: ['generate', 'deployment-contract', 'project-definition', 'baseline-upgrade'],
  },

  // The package.json manifest semantics as a ManifestDiffer (the per-generator seam).
  manifestDiffers: [packageJsonDiffer],

  listPresets() {
    return PRESET_NAMES.map((id) => ({ id, description: PRESET_INFO[id], maturity: 'stable' }));
  },

  getSchema() {
    return {
      schemaVersion: SCHEMA_VERSION,
      generatorId: GENERATOR_ID,
      options: Object.entries(OPTIONS).map(([id, spec]) => ({ id, choices: spec.choices, default: spec.default })),
    };
  },

  createProject(input) {
    return ccCreateProject(input ?? {});
  },

  exportDefinition(project) {
    return toCoreDefinition(ccExportProjectDefinition(project));
  },

  createProjectFromDefinition(definition) {
    return ccCreateProjectFromDefinition(toCreatePackkitDefinition(definition));
  },

  // The protocol boundary returns the COMMON UpgradeResult (plan.files as the
  // universal per-file vocabulary; the package.json manifest diff rides on
  // plan.manifest), so a host consumes a JS upgrade exactly like a Python one. The
  // rich, package.json-aware embedded upgradeProject (with its object-shaped plan
  // and apply policies) stays available directly for JS-specific callers.
  upgradeProject(input) {
    const { definition, ...rest } = input ?? {};
    const rich = ccUpgradeProject({
      ...rest,
      definition: definition ? toCreatePackkitDefinition(definition) : definition,
    });
    const p = rich.plan;
    const files = [
      ...p.files.added.map((path) => ({ path, status: 'new-generated', safeToApply: true, reason: 'newly generated by the current template' })),
      ...p.files.unchanged.map((path) => ({ path, status: 'unchanged', safeToApply: false, reason: 'already matches the current template' })),
      ...p.files.changed.map((path) => ({ path, ...p.files.entries[path] })),
    ].sort((a, b) => a.path.localeCompare(b.path));
    return {
      generatedProject: rich.generatedProject,
      plan: { files, baselineAvailable: p.baselineAvailable, manifest: p.packageJson },
      patch: rich.patch,
      diagnostics: rich.diagnostics,
      metadata: {
        fromVersion: rich.metadata?.fromPackkitVersion,
        toVersion: rich.metadata?.toPackkitVersion,
        baselineAvailable: p.baselineAvailable,
        hasConflicts: !!rich.metadata?.hasConflicts,
        hasSafeChanges: !!rich.metadata?.hasSafeChanges,
      },
    };
  },
};
